web:
  #build: ./images/nginx/
  image: nginx
  ports:
    - "80:80"
  volumes_from:
   - php:ro
  volumes:
  #  - ./www:/usr/share/nginx/html
    - ./conf/vhost.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  build: ./images/php
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - ./www:/var/www
    - ./teleport-cloud:/usr/local/src/teleport-cloud
    - ./conf/fpm.conf:/etc/php5/fpm/php-fpm.conf
  expose:
    - 9100
  links:
    - db
db:
  image: sameersbn/mysql
  volumes:
    - /var/lib/mysql
  environment:
    - DB_NAME=thumbsDb
    - DB_USER=thumbsUser
    - DB_PASS=thumbsPass
  expose:
    - 3306
  ports:
    - "33306:3306"
